services:
  webapp:
    image: wordpress:5.9.3-php8.0-apache
    user: "33:33"  # www-data
    ports:
      - "8080:8080"
    volumes:
      - ./wp-content:/var/www/html/wp-content
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_PASSWORD_FILE=/run/secrets/db_password
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 300M
  
  db:
    image: mysql:5.7.38
    user: "999:999"  # mysql
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M