# Build-Stage
FROM node:16 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Production-Stage
FROM node:16-alpine
WORKDIR /app
COPY --from=build /app/dist ./dist
COPY package*.json ./
RUN npm install --only=production && \
    adduser -D -h /app nodeuser && \
    chown -R nodeuser:nodeuser /app
USER nodeuser
EXPOSE 3000
CMD ["node", "dist/server.js"]