services:
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      - TIME=noon
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_PASSWORD=password
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_NAME=wordpress
    depends_on:
      - db

  db:
    image: mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
